### ISSUE TITLE
How to import it

### ISSUE THREAD

**Issue by yhhshb** [yhhshb/biolib#2]
Hi @tlemane,

Thank you for having improved the CMakeList of biolib.
Can you please provide me the correct way to import it in other projects (I'll add it to the README for documentation)?

Is there a way to specify a specific commit version by using cmake?

Thanks in advance,
-Y

**Comment by tlemane** [comment]
Hi,
See #3

**Comment by yhhshb** [comment]
Hi @tlemane ,

Thank you.
Closing this Issue.
